# The URL the site will be built for
base_url = "https://zenyaka.dev"

theme = "terminimal"
compile_sass = true
highlight_code = true
build_search_index = true

title = "Rust And The Rest"

taxonomies = [
    {name = "tags"},
]

[extra]

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "blog", url = "$BASE_URL"},

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about us", url = "$BASE_URL/about"},

    # set newtab to true to make the link open in new tab
    # {name = "github", url = "url-to-your-github", newtab = true},
]

logo_text = "Rust And The Rest"
